### PR TITLE
Fixes issue # 377 instance isn't saved. Use bulk=False or save the ob…

### PR DESCRIPTION
**Pull request by timthelion**
…ject first.

### CODE REVIEW

**Comment by timthelion** [comment]
Fixes #377

**Comment by berinhard** [comment]
@timthelion i'm sorry, but the tests are failing for django 2.0. Could you take a look at them?

**Comment by timthelion** [comment]
It's actually 2.1 which is failing. I looked at this, and I don't yet know what changed in Django2.1 from Django2.0. There's nothing about this in the release notes. I think I'll have to re-write the PR so that the problem is fixed differently. Instead of setting `bulk=False` I'll save the things that need to be saved for `bulk=True` to work. That's allegedly more efficient too from what I read (though I don't actually believe it's true because saving individual items and then bulk setting them should be the same number of round trips as setting the items individually).

**Comment by timthelion** [comment]
Git blame in the relevant sections of the django source code is showing 4 year old changes, so I'm totally baffled why this has come up now.

**Comment by anapaulagomes** [comment]
Closing this PR in favor of #396. I've tried to push my change to @timthelion's branch but I couldn't (due to permissions 😅 issues).

**Pull request closed without merging**
